services:
  - type: web
    name: pokemon-api
    runtime: python
    rootDir: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 api.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
