PLAYSTYLES = {
    "hyper_offense": {
        "name": "Hyper Offense",
        "description": "Fast, hard-hitting teams focused on overwhelming opponents quickly",
        "stat_weights": {
            "attack": 0.25,
            "special_attack": 0.25,
            "speed": 0.4,
            "hp": 0.05,
            "defense": 0.025,
            "special_defense": 0.025,
        },
        "preferred_roles": ["Sweeper", "Attacker"],
        "min_speed_tier": "Fast",
        "team_composition": {"Sweeper": 3, "Attacker": 2, "Support": 1},
    },
    "balanced": {
        "name": "Balanced",
        "description": "Well-rounded teams with mix of offense and defense",
        "stat_weights": {
            "attack": 0.15,
            "special_attack": 0.15,
            "speed": 0.2,
            "hp": 0.2,
            "defense": 0.15,
            "special_defense": 0.15,
        },
        "preferred_roles": ["Sweeper", "Tank", "Attacker", "Wall"],
        "min_speed_tier": "Medium",
        "team_composition": {"Sweeper": 2, "Tank": 1, "Attacker": 1, "Wall": 1, "Support": 1},
    },
    "stall": {
        "name": "Stall/Defensive",
        "description": "Defensive teams that outlast opponents through walls and recovery",
        "stat_weights": {
            "attack": 0.05,
            "special_attack": 0.05,
            "speed": 0.1,
            "hp": 0.3,
            "defense": 0.25,
            "special_defense": 0.25,
        },
        "preferred_roles": ["Wall", "Tank", "Support"],
        "min_speed_tier": "Slow",
        "team_composition": {"Wall": 3, "Tank": 2, "Support": 1},
    },
    "weather_rain": {
        "name": "Rain Team",
        "description": "Teams built around rain weather, boosting Water moves and Swift Swim",
        "stat_weights": {
            "attack": 0.2,
            "special_attack": 0.3,
            "speed": 0.3,
            "hp": 0.1,
            "defense": 0.05,
            "special_defense": 0.05,
        },
        "preferred_roles": ["Sweeper", "Attacker"],
        "required_types": ["water"],
        "min_speed_tier": "Fast",
        "team_composition": {"Sweeper": 3, "Attacker": 2, "Support": 1},
    },
    "trick_room": {
        "name": "Trick Room",
        "description": "Teams with slow, powerful Pokémon that thrive under Trick Room",
        "stat_weights": {
            "attack": 0.3,
            "special_attack": 0.3,
            "speed": -0.2,
            "hp": 0.2,
            "defense": 0.1,
            "special_defense": 0.1,
        },
        "preferred_roles": ["Tank", "Attacker"],
        "max_speed_tier": "Medium",
        "team_composition": {"Tank": 3, "Attacker": 2, "Support": 1},
    },
    "volt_turn": {
        "name": "Volt-Turn (Momentum)",
        "description": "Teams focused on maintaining momentum through pivoting moves",
        "stat_weights": {
            "attack": 0.2,
            "special_attack": 0.2,
            "speed": 0.3,
            "hp": 0.1,
            "defense": 0.1,
            "special_defense": 0.1,
        },
        "preferred_roles": ["Sweeper", "Attacker", "Support"],
        "min_speed_tier": "Medium",
        "team_composition": {"Sweeper": 2, "Attacker": 2, "Support": 2},
    },
    "weather_sun": {
        "name": "Sun Team",
        "description": "Drought-powered teams exploiting Chlorophyll and Solar Power",
        "stat_weights": {
            "attack": 0.15,
            "special_attack": 0.35,
            "speed": 0.25,
            "hp": 0.1,
            "defense": 0.05,
            "special_defense": 0.1,
        },
        "preferred_roles": ["Sweeper", "Attacker"],
        "required_types": ["fire", "grass"],
        "min_speed_tier": "Fast",
        "team_composition": {"Sweeper": 3, "Attacker": 2, "Support": 1},
    },
    "weather_sand": {
        "name": "Sand Team",
        "description": "Sandstream-driven teams with Sand Rush and Sand Force abusers",
        "stat_weights": {
            "attack": 0.25,
            "special_attack": 0.15,
            "speed": 0.2,
            "hp": 0.15,
            "defense": 0.15,
            "special_defense": 0.1,
        },
        "preferred_roles": ["Tank", "Attacker", "Sweeper"],
        "required_types": ["rock", "ground", "steel"],
        "min_speed_tier": "Medium",
        "team_composition": {"Tank": 2, "Attacker": 2, "Sweeper": 1, "Support": 1},
    },
    "weather_snow": {
        "name": "Snow / Aurora Veil",
        "description": "Ice-type stacking with Aurora Veil support for setup sweepers",
        "stat_weights": {
            "attack": 0.2,
            "special_attack": 0.2,
            "speed": 0.15,
            "hp": 0.15,
            "defense": 0.15,
            "special_defense": 0.15,
        },
        "preferred_roles": ["Wall", "Sweeper", "Support"],
        "required_types": ["ice"],
        "min_speed_tier": "Medium",
        "team_composition": {"Wall": 2, "Sweeper": 2, "Support": 1, "Tank": 1},
    },
    "bulky_offense": {
        "name": "Bulky Offense",
        "description": "Powerful but durable — hit hard while taking hits, no glass cannons",
        "stat_weights": {
            "attack": 0.2,
            "special_attack": 0.2,
            "speed": 0.15,
            "hp": 0.2,
            "defense": 0.125,
            "special_defense": 0.125,
        },
        "preferred_roles": ["Tank", "Attacker"],
        "min_speed_tier": "Medium",
        "team_composition": {"Tank": 3, "Attacker": 2, "Support": 1},
    },
    "hazard_stack": {
        "name": "Hazard Stack",
        "description": "Stealth Rock + Spikes layers with spinblockers and chip damage",
        "stat_weights": {
            "attack": 0.1,
            "special_attack": 0.1,
            "speed": 0.15,
            "hp": 0.25,
            "defense": 0.2,
            "special_defense": 0.2,
        },
        "preferred_roles": ["Wall", "Support", "Tank"],
        "min_speed_tier": "Slow",
        "team_composition": {"Wall": 2, "Support": 2, "Tank": 1, "Sweeper": 1},
    },
    "setup_sweeper": {
        "name": "Setup Sweeper",
        "description": "Dragon Dance / Swords Dance / Nasty Plot cores with fast revenge killers",
        "stat_weights": {
            "attack": 0.3,
            "special_attack": 0.25,
            "speed": 0.3,
            "hp": 0.05,
            "defense": 0.05,
            "special_defense": 0.05,
        },
        "preferred_roles": ["Sweeper", "Attacker"],
        "min_speed_tier": "Fast",
        "team_composition": {"Sweeper": 4, "Support": 1, "Wall": 1},
    },
    "hyper_stall": {
        "name": "Hyper Stall",
        "description": "Six walls — PP stall, Toxic, Encore, and endless recovery loops",
        "stat_weights": {
            "attack": 0.0,
            "special_attack": 0.0,
            "speed": 0.05,
            "hp": 0.35,
            "defense": 0.3,
            "special_defense": 0.3,
        },
        "preferred_roles": ["Wall", "Support"],
        "min_speed_tier": "Slow",
        "team_composition": {"Wall": 4, "Support": 2},
    },
    "status_spread": {
        "name": "Status Spreading",
        "description": "Paralysis, burn, toxic and cleric support to cripple the opponent",
        "stat_weights": {
            "attack": 0.05,
            "special_attack": 0.1,
            "speed": 0.15,
            "hp": 0.25,
            "defense": 0.2,
            "special_defense": 0.25,
        },
        "preferred_roles": ["Support", "Wall", "Tank"],
        "min_speed_tier": "Medium",
        "team_composition": {"Support": 3, "Wall": 2, "Sweeper": 1},
    },
    "dragon_core": {
        "name": "Dragon Core",
        "description": "Dragon-type spam backed by a Fairy answer and Steel-type coverage",
        "stat_weights": {
            "attack": 0.25,
            "special_attack": 0.25,
            "speed": 0.25,
            "hp": 0.1,
            "defense": 0.075,
            "special_defense": 0.075,
        },
        "preferred_roles": ["Sweeper", "Attacker", "Tank"],
        "required_types": ["dragon"],
        "min_speed_tier": "Fast",
        "team_composition": {"Sweeper": 3, "Attacker": 1, "Tank": 1, "Support": 1},
    },
    "baton_pass": {
        "name": "Baton Pass Chain",
        "description": "Setup boosters passing stat boosts to a devastating receiver",
        "stat_weights": {
            "attack": 0.15,
            "special_attack": 0.15,
            "speed": 0.3,
            "hp": 0.2,
            "defense": 0.1,
            "special_defense": 0.1,
        },
        "preferred_roles": ["Support", "Sweeper"],
        "min_speed_tier": "Medium",
        "team_composition": {"Support": 3, "Sweeper": 2, "Wall": 1},
    },
}


def get_playstyle(name: str) -> dict:
    return PLAYSTYLES.get(name, PLAYSTYLES["balanced"])


def get_all_playstyles() -> list:
    return [
        {"key": k, "name": v["name"], "description": v["description"]}
        for k, v in PLAYSTYLES.items()
    ]
